language: node_js
node_js:
  - "8.9"

# cache node modules to make the build faster
cache:
  directories:
    - node_modules

script:
  # check the code meets coding standards
  - npm run lint:css
  - npm run lint:js
  # do a production build
  - npm build 
  # run the unit tests
  - npm test
  # run the e2e tests
  - npm run e2e