matrix:
  fast_finish: true
language: node_js
node_js:
- '8.9'
cache:
  directories:
  - node_modules
install:
- npm install -g codecov
- npm install
script:
- npm run lint:css
- npm run lint:js
- npm run build
- npm run test
- codecov
- npm run e2e
before_deploy:
  - chmod +x $TRAVIS_BUILD_DIR/continuous_integration/package_artifacts.sh
  - $TRAVIS_BUILD_DIR/continuous_integration/package_artifacts.sh $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  api_key:
    secure: Nzws/rGOzhB+0LQbqTzfzD12Gl5KGYcGUKdOwmb5PHF0/V1SJTRhZX2NVH4WBS/wMqUqYIp/K0jxneGKCLqgb6BXumnddHDTfBT/waO526hHMZ4tJv+AiUmtg/CythoNytdPgDlmWYzjpRYvfDwVENwkje/pDnm76JJdyEE351IbNFxLqGs2uzWqKd72ZduKhvUs+KwSrCCephQqPvKqXq/7fiGdngC3U/hx7eXMdF2/F8ZEY60WGMlTRa1Ncsi184FyZwwbuxNRLtrMmXwU4z79shnZ/GuG6GJqK/KI5aNaY0XP0wv7xR4BvE0KPAVcRfphTk6A/HHYi5GsrhEQXOnBY+1caLkSdUqd+E8yZOWGckL50N9RZhDWdSvgkO50F6E4JVDRY7t0LQK2OoBBKoy4ovcRHZG8itdQUhXIQD/2nWlBSZjffRaVAHfBEAgq+m2Ot/61Cu/fqDS5eFuViy530Ohai1z1G+oZKFpsiC2wDDRQex8hhXIeWo14nZnfeXlp9djO4NvsscpOEeyAcMpy9xzB5XdlMP5zq2UTOaGi6MRsUmjORRCkjd1F/p73tN9D2nBtLgPDCgChShelzCiKPyJTKGySXublWVQiaoSY3osVwUPCQU2I4fR2/UD5aYFTTCrrYTscrgZhgwh/h9dQXv+4huFN9PULN9Rh88k=
  file_glob: true
  file: ${TRAVIS_BUILD_DIR}/artifacts/*
  skip_cleanup: true
  on:
    repo: dls-controls/malcolmjs
    all_branches: true
    tags: true
