@startuml
MainPane -> panelActions: toggle sidebar
Activate panelActions
panelActions -> AppDispatcher: action
Activate AppDispatcher
AppDispatcher -> paneStore: action
Activate paneStore
paneStore -> sidebar: sidebar open state
Activate sidebar
@enduml