@startuml
class MainPane {
-handleToggleSidebar()
-handleToggleFooter()
-handleActionBlockLookupTableTabOpen()
Panel : reactPanels.Panel
Tab : reactPanels.Tab
Toolbar : reactPanels.Toolbar
Content : reactPanels.Content
Footer : reactPanels.Footer
ToggleButton : reactPanels.ToggleButton
Button : reactPanels.Button
}

package react-panels {
MainPane <|-- reactPanels
}

class paneActions{
+toggleSidebar()
}
toggleSidebar()- paneActions
MainPane *-- paneActions : use

@enduml